Repository jakartaee/data, pull requests merged in 2022-10, with the labels that each got.

#32 remaining documentation updates for Limit
  api/src/main/java/jakarta/data/repository/Limit.java
  api/src/main/java/jakarta/data/repository/Pageable.java
  api/src/main/java/jakarta/data/repository/Repository.java
  api/src/main/java/jakarta/data/repository/Sort.java
  spec/src/main/asciidoc/repository.asciidoc
Labels: enhancement

#40 Bump nexus-staging-maven-plugin from 1.6.3 to 1.6.13 and add missing …
  pom.xml
Labels: enhancement

#33 Replacing assertion libraries: Hamcrest by AssertJ
  CHANGELOG.md
  api/pom.xml
  api/src/test/java/jakarta/data/repository/PageableTest.java
  api/src/test/java/jakarta/data/repository/SortTest.java
  pom.xml
Labels: test

#49 Add reference to Jakarta EE logo in jakarta-data.asciidoc file
  spec/src/main/asciidoc/jakarta-data.asciidoc
Labels: documentation

#56 Restructure directory for specification documents and update some doc…
  spec/src/main/asciidoc/architecture.asciidoc
  spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc
  spec/src/main/asciidoc/chapters/introduction/project_team.adoc
  spec/src/main/asciidoc/chapters/license/license-alv2.asciidoc
  spec/src/main/asciidoc/chapters/license/license-efsl.adoc
  spec/src/main/asciidoc/jakarta-data-introduction.asciidoc
  spec/src/main/asciidoc/jakarta-data.asciidoc
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#60 Move the readme and other docs to use asciidoc as default
  CHANGELOG.adoc
  CHANGELOG.md
  CONTRIBUTING.adoc
  NOTICE.adoc
  README.adoc
  README.md
  SECURITY.adoc
Labels: documentation
