Repository jakartaee/data, pull requests merged in 2022-09, with the labels that each got.

#13 fix HTML5 errors in JavaDoc
  api/src/main/java/jakarta/data/repository/Repository.java
Labels: bug

#16 Add crud repository feature
  api/src/main/java/jakarta/data/repository/CrudRepository.java
  api/src/main/java/jakarta/data/repository/Param.java
  api/src/main/java/jakarta/data/repository/Query.java
  spec/pom.xml
  spec/src/main/asciidoc/images/01-repository.png
  spec/src/main/asciidoc/images/02-repositories.png
  spec/src/main/asciidoc/jakarta-data-introduction.asciidoc
  spec/src/main/asciidoc/jakarta-data.asciidoc
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation, enhancement

#25 Add meeting minutes and calendar links on readme/main page
  README.md
Labels: documentation
