Repository jakartaee/data, pull requests merged in 2022-11, with the labels that each got.

#61 Improve readme with more project information
  README.adoc
Labels: documentation

#62 page count when using Query annotation
  api/src/main/java/jakarta/data/repository/Query.java
Labels: enhancement

#59 Add Streamable interface
  api/src/main/java/jakarta/data/repository/Slice.java
  api/src/main/java/jakarta/data/repository/Streamable.java
Labels: design
