Repository jakartaee/data, pull requests merged in 2023-09, with the labels that each got.

#240 more documentation about the save parameter and return value
  api/src/main/java/jakarta/data/repository/CrudRepository.java
Labels: bug, documentation

#231 corrections and clarifications to Jakarta Validation section
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/jakarta-ee.adoc
Labels: bug, documentation, design

#245 Proposal: Define basic terms: "entity", "repository", "identifier", etc.
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation, help wanted, jpa, nosql

#249 Keyword list consistency with JavaDoc and BNF
  spec/src/main/asciidoc/repository.asciidoc
Labels: bug, documentation

#248 accessor method to obtain EntityManager
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/repository.asciidoc
Labels: design

#251 TCK test for EntityManager method
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
Labels: test

#247 Define the minimal set of portable functionality
  api/src/main/java/jakarta/data/repository/CrudRepository.java
  api/src/main/java/jakarta/data/repository/Pageable.java
  api/src/main/java/jakarta/data/repository/PageableRepository.java
  spec/README.adoc
  spec/pom.xml
  spec/src/main/asciidoc/jakarta-data.adoc
  spec/src/main/asciidoc/portability.asciidoc
  spec/src/main/asciidoc/repository.asciidoc
Labels: help wanted

#252 Include per-database-type keyword limitations in JavaDoc
  api/src/main/java/module-info.java
Labels: documentation

#261 refactor packages
  api/src/main/java/jakarta/data/Direction.java
  api/src/main/java/jakarta/data/Limit.java
  api/src/main/java/jakarta/data/Sort.java
  api/src/main/java/jakarta/data/Streamable.java
  api/src/main/java/jakarta/data/page/KeysetAwarePage.java
  api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
  api/src/main/java/jakarta/data/page/KeysetCursor.java
  api/src/main/java/jakarta/data/page/Page.java
  api/src/main/java/jakarta/data/page/Pageable.java
  api/src/main/java/jakarta/data/page/Pagination.java
  api/src/main/java/jakarta/data/page/Slice.java
  api/src/main/java/jakarta/data/page/package-info.java
  api/src/main/java/jakarta/data/repository/OrderBy.java
  api/src/main/java/jakarta/data/repository/PageableRepository.java
  api/src/main/java/jakarta/data/repository/Query.java
  api/src/main/java/module-info.java
  api/src/test/java/jakarta/data/LimitTest.java
  api/src/test/java/jakarta/data/SortTest.java
  api/src/test/java/jakarta/data/page/KeysetPageableTest.java
  api/src/test/java/jakarta/data/page/PageableTest.java
  api/src/test/java/jakarta/data/page/PaginationTest.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/IdOperations.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
Labels: design

#263 JavaDoc needs to include parameter-based queries
  api/src/main/java/module-info.java
Labels: documentation

#266 Specify parameter-based queries/methods in spec doc
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#268 Fix two CrudRepository method names that do not follow the spec rules
  api/src/main/java/jakarta/data/repository/BasicRepository.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/ReadOnlyRepository.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
Labels: bug

#275 Renames that were missed in JavaDoc, spec, and TCK
  README.adoc
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/jakarta-ee.adoc
  spec/src/main/asciidoc/portability.asciidoc
  spec/src/main/asciidoc/repository.asciidoc
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
Labels: bug
