Repository jakartaee/data, pull requests merged in 2023-11, with the labels that each got.

#324 Fix jruby dependency
  tck-dist/pom.xml
Labels: dependencies

#321 TCK tests for life cycle methods
  api/src/main/java/jakarta/data/repository/Delete.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
Labels: test

#329 Include precedence for repository methods in user-facing JavaDoc
  api/src/main/java/module-info.java
Labels: documentation

#333 Clarify description of pagination approach used in example
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#334 document persistence context requirements for initial version of spec
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/jakarta-ee.adoc
Labels: documentation

#335 More complete documentation of primary entity type
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#341 TCK tests for primary entity type and By
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/CustomRepository.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: test

#345 help users locate the main Jakarta Data overview page in JavaDoc
  api/src/main/java/jakarta/data/package-info.java
  api/src/main/java/jakarta/data/page/package-info.java
  api/src/main/java/jakarta/data/repository/Repository.java
  api/src/main/java/jakarta/data/repository/package-info.java
Labels: documentation

#344 Review of Entity Classes section
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#343 proofread section 2 Repository and 2.1 Repositories on Jakarta Data
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#342 review of introduction and goals section
  spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc
Labels: documentation

#350 proofread section 4.8: pagination
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#349 Review section 4 on Repository Interfaces, except for pagination
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#352 review section 5: Interoperability with Jakarta EE specs
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/jakarta-ee.adoc
Labels: documentation

#351 Removing Paging Justification
  spec/src/main/asciidoc/images/02-pagination.png
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#355 review of section 7 on Portability
  spec/src/main/asciidoc/portability.asciidoc
Labels: documentation

#357 Include example with data for keyset pagination
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#358 improve visibility of table rows in javadoc
  api/src/main/java/module-info.java
Labels: documentation

#348 Create validation tests
  pom.xml
  tck/pom.xml
  tck/src/main/java/ee/jakarta/tck/data/web/validation/Rectangle.java
  tck/src/main/java/ee/jakarta/tck/data/web/validation/Rectangles.java
  tck/src/main/java/ee/jakarta/tck/data/web/validation/ValidationTests.java
Labels: test

#359 review of pagination JavaDoc
  api/src/main/java/jakarta/data/page/KeysetAwarePage.java
  api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
  api/src/main/java/jakarta/data/page/Page.java
  api/src/main/java/jakarta/data/page/Pageable.java
  api/src/main/java/jakarta/data/page/Slice.java
  api/src/main/java/jakarta/data/page/package-info.java
  api/src/main/java/jakarta/data/repository/OrderBy.java
  api/src/test/java/jakarta/data/page/KeysetPageableTest.java
  spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc
Labels: documentation

#360 review of JavaDoc in the jakarta.data package
  api/src/main/java/jakarta/data/Limit.java
  api/src/main/java/jakarta/data/Sort.java
  api/src/main/java/jakarta/data/Streamable.java
Labels: documentation

#364 review of the repository package JavaDoc
  api/src/main/java/jakarta/data/repository/BasicRepository.java
  api/src/main/java/jakarta/data/repository/By.java
  api/src/main/java/jakarta/data/repository/CrudRepository.java
  api/src/main/java/jakarta/data/repository/DataRepository.java
  api/src/main/java/jakarta/data/repository/Delete.java
  api/src/main/java/jakarta/data/repository/Insert.java
  api/src/main/java/jakarta/data/repository/OrderBy.java
  api/src/main/java/jakarta/data/repository/PageableRepository.java
  api/src/main/java/jakarta/data/repository/Param.java
  api/src/main/java/jakarta/data/repository/Query.java
  api/src/main/java/jakarta/data/repository/Repository.java
  api/src/main/java/jakarta/data/repository/Save.java
  api/src/main/java/jakarta/data/repository/Update.java
Labels: documentation

#368 Entity Property Names section belongs under Entity Classes, not Query by Method Name
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#371 TCK tests for BasicRepository built-in methods
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/Box.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/Boxes.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: test

#372 preliminary review for conciseness
  spec/src/main/asciidoc/chapters/introduction/introduction.asciidoc
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#376 Update signatures
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
Labels: test

#382 Update copyright with real values
  spec/src/main/asciidoc/chapters/license/license-efsl.adoc
  spec/src/main/asciidoc/jakarta-data.adoc
Labels: documentation

#383 Update committer list
  spec/src/main/asciidoc/chapters/introduction/project_team.adoc
Labels: documentation

#384 Typo in release workflow
  .github/workflows/release.yml
Labels: github_actions
