Repository jakartaee/data, pull requests merged in 2023-10, with the labels that each got.

#277 TCK tests for find queries using parameter names
  tck/pom.xml
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
Labels: test

#283 insert and update methods on built-in repository
  api/src/main/java/jakarta/data/exceptions/EntityExistsException.java
  api/src/main/java/jakarta/data/repository/BasicRepository.java
Labels: design

#285 tests for StaticMetamodel
  api/src/main/resources/checkstyle.xml
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacter_.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTest.java
Labels: test

#293 Align JavaDoc with spec updates from 273
  api/src/main/java/module-info.java
Labels: documentation

#276 Update signature files and signature generation
  tck/pom.xml
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/README.md
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
Labels: documentation, test

#302 TCK test for metamodel class generated at build time
  api/pom.xml
  api/src/main/java/jakarta/data/model/StaticMetamodel.java
  pom.xml
  spec/src/main/asciidoc/repository.asciidoc
  tck/pom.xml
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiChar_.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacter_.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: design, test

#319 TCK tests are missing the Save annotation on lifecycle methods
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/ReadOnlyRepository.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/Catalog.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
Labels: bug, test
