Repository jakartaee/data, pull requests merged in 2024-04, with the labels that each got.

#621 TCK superinterface is no longer valid
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/IdOperations.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: bug, test

#625 documentation is lacking for implied equals on Query by Method Name
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/repository.asciidoc
Labels: bug, documentation

#652 TCK broken by #639
  api/src/main/java/jakarta/data/page/Pagination.java
  api/src/main/java/jakarta/data/repository/BasicRepository.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: bug, test

#649 Fix QBN issue in CDI tests
  tck/pom.xml
  tck/src/main/java/ee/jakarta/tck/data/common/cdi/Directory.java
  tck/src/main/java/ee/jakarta/tck/data/common/cdi/DirectoryRepository.java
  tck/src/main/java/ee/jakarta/tck/data/common/cdi/PutTCKLifecyleMethod.java
  tck/src/main/java/ee/jakarta/tck/data/core/cdi/ExtensionTests.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
  tck/src/main/java/ee/jakarta/tck/data/web/cdi/ExtensionTests.java
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
Labels: test

#647 EntityDefining was added without updating TCK
  tck/src/main/java/ee/jakarta/tck/data/common/cdi/PersonEntity.java
Labels: bug, test

#666 Static metamodel examples show bad coding practices
  api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java
  api/src/main/java/jakarta/data/metamodel/package-info.java
  spec/src/main/asciidoc/entity.asciidoc
Labels: bug, documentation

#664 Fix invalid method name in JavaDoc
  api/src/main/java/module-info.java
Labels: bug, documentation

#665 Fix more javadoc broken by the PageRequest/Sort decoupling
  api/src/main/java/jakarta/data/page/CursoredPage.java
  api/src/main/java/jakarta/data/page/PageRequest.java
  api/src/main/java/jakarta/data/page/package-info.java
  api/src/main/java/jakarta/data/repository/BasicRepository.java
  api/src/main/java/module-info.java
Labels: bug, documentation

#678 give cursor TCK tests a meaningful page number rather than defaulting to 1
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: test

#683 PageRequest toString wrongly states a cursor has multiple keys
  api/src/main/java/jakarta/data/page/PageRequestCursor.java
  api/src/main/java/jakarta/data/page/Pagination.java
  api/src/test/java/jakarta/data/page/PageRequestCursorTest.java
Labels: bug

#685 more improvements to the presentation of the QbMN feature
  spec/src/main/asciidoc/method-query.asciidoc
Labels: documentation

#663 use @Query and @Find for example code in chapter 4
  spec/src/main/asciidoc/repository.asciidoc
Labels: documentation

#684 JavaDoc needs to align with recent changes to method name grammar
  api/src/main/java/module-info.java
Labels: bug, documentation

#686 beforeKey and afterKey were missed in some examples
  api/src/main/java/jakarta/data/page/CursoredPage.java
  spec/src/main/asciidoc/repository.asciidoc
Labels: bug, documentation

#695 Upgrade to 2.3 signature test plugin
  pom.xml
  tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc
  tck-dist/src/main/asciidoc/sections/04prereq.adoc
  tck-dist/src/main/starter/ee-pom.xml
  tck-dist/src/main/starter/se-pom.xml
  tck/src/main/java/ee/jakarta/tck/data/framework/arquillian/extensions/TCKArchiveProcessor.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/README.md
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_17
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/jakarta.data.sig_21
Labels: test

#697 Missing word in PageRequest javadoc
  api/src/main/java/jakarta/data/page/PageRequest.java
Labels: bug, documentation

#698 Fix signature testing after upgrade to jakarta.tck signature test plugin
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/ApiCheckDriver.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/DataSignatureTestRunner.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/PackageList.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTest.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestData.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestDriver.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/SigTestEE.java
  tck/src/main/java/ee/jakarta/tck/data/framework/signature/SignatureTestDriver.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
  tck/src/main/resources/ee/jakarta/tck/data/framework/signature/sig-test-pkg-list.txt
Labels: test

#620 TCK test for ID(THIS)
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: test

#707 Use web archive instead of java archive for standalone
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/example/StandaloneExampleTests.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/nosql/example/NoSQLEntityTests.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
  tck/src/main/java/ee/jakarta/tck/data/web/cdi/provider/AddressRepositoryProducer.java
  tck/src/main/java/ee/jakarta/tck/data/web/cdi/provider/ExtensionImpl.java
  tck/src/main/java/ee/jakarta/tck/data/web/example/SimpleServletExampleTests.java
Labels: bug, test

#702 Fix required property jakarta.tck.profile
  tck-dist/src/main/asciidoc/sections/07.1se-mode.adoc
  tck-dist/src/main/asciidoc/sections/07.2ee-mode.adoc
  tck-dist/src/main/starter/ee-pom.xml
  tck-dist/src/main/starter/se-pom.xml
  tck/src/main/java/ee/jakarta/tck/data/framework/junit/anno/Standalone.java
  tck/src/main/java/ee/jakarta/tck/data/framework/junit/extensions/StandaloneExtension.java
  tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestProperty.java
  tck/src/main/java/ee/jakarta/tck/data/framework/utilities/TestPropertyUtility.java
Labels: bug, test
