Repository jakartaee/data, pull requests merged in 2024-02, with the labels that each got.

#433 Missing Sort in TCK test
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: bug, test

#432 Sort with type parameter
  api/src/main/java/jakarta/data/Limit.java
  api/src/main/java/jakarta/data/Order.java
  api/src/main/java/jakarta/data/Sort.java
  api/src/main/java/jakarta/data/metamodel/SortableAttribute.java
  api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java
  api/src/main/java/jakarta/data/metamodel/TextAttribute.java
  api/src/main/java/jakarta/data/metamodel/package-info.java
  api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
  api/src/main/java/jakarta/data/page/Page.java
  api/src/main/java/jakarta/data/page/Pageable.java
  api/src/main/java/jakarta/data/page/Pagination.java
  api/src/main/java/jakarta/data/page/Slice.java
  api/src/main/java/jakarta/data/page/package-info.java
  api/src/main/java/jakarta/data/repository/CrudRepository.java
  api/src/main/java/jakarta/data/repository/OrderBy.java
  api/src/main/java/jakarta/data/repository/PageableRepository.java
  api/src/main/java/jakarta/data/repository/Param.java
  api/src/main/java/jakarta/data/repository/Query.java
  api/src/main/java/module-info.java
  api/src/test/java/jakarta/data/SortTest.java
  api/src/test/java/jakarta/data/page/KeysetPageableTest.java
  api/src/test/java/jakarta/data/page/PageableTest.java
  api/src/test/java/jakarta/data/page/PaginationTest.java
  spec/src/main/asciidoc/repository.asciidoc
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/IdOperations.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_AsciiChar.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_AsciiCharacter.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/Catalog.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
Labels: design

#443 Update the TCK and other missed places for the Find annotation
  api/src/main/java/jakarta/data/page/Slice.java
  api/src/main/java/jakarta/data/repository/BasicRepository.java
  api/src/main/java/jakarta/data/repository/By.java
  api/src/main/java/jakarta/data/repository/Delete.java
  api/src/main/java/jakarta/data/repository/Insert.java
  api/src/main/java/jakarta/data/repository/PageableRepository.java
  api/src/main/java/jakarta/data/repository/Save.java
  api/src/main/java/jakarta/data/repository/Update.java
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/repository.asciidoc
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/AsciiCharacters.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/PositiveIntegers.java
Labels: documentation, test

#447 Fix release workflow
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/tck-challenge.yml
  .github/workflows/release.yml
Labels: github_actions

#465 Additional renames of Pageable to PageRequest
  README.adoc
  TESTING-GUIDELINE.adoc
  api/src/main/java/jakarta/data/Order.java
  api/src/main/java/jakarta/data/metamodel/StaticMetamodel.java
  api/src/main/java/jakarta/data/metamodel/package-info.java
  api/src/main/java/jakarta/data/page/KeysetAwareSlice.java
  api/src/main/java/jakarta/data/page/Page.java
  api/src/main/java/jakarta/data/page/Pagination.java
  api/src/main/java/jakarta/data/page/Slice.java
  api/src/main/java/jakarta/data/page/package-info.java
  api/src/main/java/jakarta/data/repository/BasicRepository.java
  api/src/main/java/jakarta/data/repository/OrderBy.java
  api/src/main/java/jakarta/data/repository/Param.java
  api/src/main/java/jakarta/data/repository/Query.java
  api/src/main/java/module-info.java
  api/src/test/java/jakarta/data/page/KeysetPageRequestTest.java
  api/src/test/java/jakarta/data/page/PageRequestTest.java
  api/src/test/java/jakarta/data/page/PaginationTest.java
  spec/src/main/asciidoc/portability.asciidoc
  spec/src/main/asciidoc/repository.asciidoc
Labels: bug

#479 Fix error in validation tests
  tck/src/main/java/ee/jakarta/tck/data/web/validation/Rectangles.java
Labels: bug

#483 more precise wording around transaction enlistment
  spec/src/main/asciidoc/jakarta-ee.adoc
Labels: documentation

#481 Update after release 1.0.0-M3
  .github/ISSUE_TEMPLATE/release.yml
  CHANGELOG.adoc
  README.adoc
Labels: documentation

#494 Attribute is missing type
  api/src/main/java/jakarta/data/metamodel/Attribute.java
  api/src/main/java/jakarta/data/metamodel/SortableAttribute.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_AsciiChar.java
Labels: bug

#502 CrudRepository update contradicts new lifecycle method javadoc and TCK broken
  api/src/main/java/jakarta/data/repository/CrudRepository.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/persistence/PersistenceEntityTests.java
Labels: bug
