Repository jakartaee/data, pull requests merged in 2025-05, with the labels that each got.

#1087 Javadoc for Restriction
  api/src/main/java/jakarta/data/metamodel/Attribute.java
  api/src/main/java/jakarta/data/restrict/BasicRestriction.java
  api/src/main/java/jakarta/data/restrict/BasicRestrictionRecord.java
  api/src/main/java/jakarta/data/restrict/CompositeRestriction.java
  api/src/main/java/jakarta/data/restrict/Restrict.java
  api/src/main/java/jakarta/data/restrict/Restriction.java
  api/src/test/java/jakarta/data/restrict/BasicRestrictionRecordTest.java
  api/src/test/java/jakarta/data/restrict/CompositeRestrictionRecordTest.java
  api/src/test/java/jakarta/data/restrict/TextRestrictionRecordTest.java
Labels: documentation

#1091 Javadoc for Expression
  api/src/main/java/jakarta/data/expression/Expression.java
  api/src/main/java/jakarta/data/metamodel/Attribute.java
  api/src/main/java/jakarta/data/restrict/Restriction.java
  api/src/test/java/jakarta/data/metamodel/AttributeTest.java
Labels: documentation

#1081 ignore: jruby 10.0.0.0
  .github/dependabot.yml
Labels: dependencies

#1097 fix: toolchain error java 25
  .github/workflows/ci.yml
  .github/workflows/update.yml
Labels: github_actions

#1093 javadoc for comparable expressions
  api/src/main/java/jakarta/data/expression/ComparableExpression.java
  api/src/main/java/jakarta/data/expression/Expression.java
  api/src/main/java/jakarta/data/expression/NumericExpression.java
  api/src/main/java/jakarta/data/expression/TemporalExpression.java
  api/src/main/java/jakarta/data/expression/TextExpression.java
  api/src/main/java/jakarta/data/metamodel/Attribute.java
Labels: documentation

#1106 Module Javadoc should mention Restriction and prefer Constraints over Query by Method Name
  api/src/main/java/jakarta/data/metamodel/package-info.java
  api/src/main/java/module-info.java
Labels: documentation

#1108 Document same limitation for First annotation as for First keyword
  api/src/main/java/jakarta/data/page/PageRequest.java
Labels: documentation
