Repository jakartaee/data, pull requests merged in 2025-02, with the labels that each got.

#921 subset of entity attributes - Find methods
  api/src/main/java/jakarta/data/repository/Find.java
  api/src/main/java/jakarta/data/repository/Select.java
  api/src/main/java/module-info.java
  spec/src/main/asciidoc/repository.asciidoc
Labels: enhancement

#964 TCK tests of record result types where record component names match the entity attributes
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NumberInfo.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/_NaturalNumber.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: test

#967 Allow NoSQL to defer request for totals and raise UnsupportedOperationException later
  api/src/main/java/jakarta/data/page/PageRequest.java
Labels: documentation

#969 TCK test of record result types where the repository method uses Select to identify the entity attributes because record component names do not match
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/NaturalNumbers.java
  tck/src/main/java/ee/jakarta/tck/data/framework/read/only/WholeNumber.java
  tck/src/main/java/ee/jakarta/tck/data/standalone/entity/EntityTests.java
Labels: test

#985 Find value should be annotation member, not a constant
  api/src/main/java/jakarta/data/repository/Find.java
Labels: bug

#996 fix: add junit-platform-launcher
  tck-dist/src/main/starter/ee-pom.xml
  tck-dist/src/main/starter/se-pom.xml
  tck/pom.xml
Labels: test, dependencies
